kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Values.cheese }}
  labels:
    app: cheese
    cheese: {{ .Values.cheese }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cheese
      task: {{ .Values.cheese }}
  template:
    metadata:
      labels:
        app: cheese
        task: {{ .Values.cheese }}
        version: v0.0.1
    spec:
      containers:
      - name: cheese
        image: errm/cheese:{{ .Values.cheese }}
        ports:
        - containerPort: 80