apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cheese-{{ .Values.cheese }}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.cheese }}.minikube
    http:
      paths:
      - path: /
        backend:
          serviceName: {{ .Values.cheese }}
          servicePort: http